length: 1460
username_length: 10
encoding_type: 'utf-8'
bits_per_symbol: 8

server:
  ip: '127.0.0.1'
  port: 1234

normal_delay:
  left: 0.75
  right: 1.25

ip_ctc:
  0:
    left: 6
    right: 12
  1:
    left: 16
    right: 22

covert: True
covert_message: 'Qwerty12345'
embed_every: 3
number_of_messages: 25

path_to_messages: '../data/text_messages.csv'
longest_message_length: 100

save: False
path_to_save_file:
  overt: '../data/overt_traffic.pkl'
  covert:
    1: '../data/covert_traffic_1.pkl'
    3: '../data/covert_traffic_3.pkl'

